### ISSUE TITLE
whats the best way to hash/salt should i use sha 256 or 128?

### ISSUE THREAD

**Issue by JoArtMahilaga** [DraganD-Ukr/Web-Patterns-CA1#5]
Having a difficulty to decide between using sha 256/128? should i put it in the DAO implementation or  have a separate method in the business class to handle the hashing?

**Comment by DraganD-Ukr** [comment]
1. We haven't discussed hashing/salting password with Michelle, however i think this would be a nice feature Jo!

2. You should go with 256, but i suggest you using library like **[JBCrypt](https://mvnrepository.com/artifact/org.mindrot/jbcrypt/0.4)** for easier use and ensuring much stronger security

3. Having a separate method or even a class to handle the hahing would make more sense rather than doing it in DAO

Tag me or call on discord if you have any questions

**Comment by DraganD-Ukr** [comment]
Issues closed: agreed on using JBCrypt
